# Generated by Django 3.0.8 on 2020-08-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamform',
            name='logouri',
            field=models.ImageField(upload_to='media/team'),
        ),
    ]
