# Generated by Django 3.0.8 on 2020-08-18 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0003_auto_20200819_0137'),
    ]

    operations = [
        migrations.CreateModel(
            name='matches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_winner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='winner', to='team.teamform')),
                ('team_one', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_team', to='team.teamform')),
                ('team_two', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='away_team', to='team.teamform')),
            ],
        ),
    ]
