# Generated by Django 3.0.8 on 2020-08-20 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_auto_20200820_0619'),
        ('match', '0003_remove_matches_teams'),
    ]

    operations = [
        migrations.CreateModel(
            name='match_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.IntegerField(default=0)),
                ('wicket', models.IntegerField(default=0)),
                ('matchid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matchid', to='match.matches')),
                ('playerid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='playerid', to='player.players')),
            ],
        ),
    ]
