# Generated by Django 3.0.8 on 2020-08-20 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0004_match_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='matchname',
            field=models.CharField(default='NULL', max_length=50),
        ),
    ]
