# Generated by Django 3.0.8 on 2020-08-18 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0003_auto_20200819_0137'),
    ]

    operations = [
        migrations.CreateModel(
            name='players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('imageUri', models.ImageField(upload_to='player')),
                ('playernum', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('totalmatches', models.IntegerField(default=0)),
                ('totalruns', models.IntegerField(default=0)),
                ('highestscore', models.IntegerField(default=0)),
                ('fifties', models.IntegerField(default=0)),
                ('hundreds', models.IntegerField(default=0)),
                ('teamid', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='team.teamform')),
            ],
        ),
    ]
